
#function sub {
./bat.sh m2cross
./bat.sh maccum
./bat.sh mavg
./bat.sh mbest
./bat.sh mbucket
./bat.sh mcat
./bat.sh mchgnum
./bat.sh mchgstr
./bat.sh mcombi
./bat.sh mcommon
./bat.sh mcut
./bat.sh msum
./bat.sh mcount
./bat.sh mcross
./bat.sh mdelnull
./bat.sh mdformat
./bat.sh mduprec
./bat.sh mfldname
./bat.sh mfsort
./bat.sh mhashavg
./bat.sh mhashsum
./bat.sh mjoin
./bat.sh mkeybreak
./bat.sh mmbucket
./bat.sh mmvavg
./bat.sh mmvsim
./bat.sh mmvstats
./bat.sh mnewnumber
./bat.sh mnewrand
./bat.sh mnewstr
./bat.sh mnjoin
./bat.sh mnormalize
./bat.sh mnrcommon
./bat.sh mnrjoin
./bat.sh mnullto
./bat.sh mnumber
./bat.sh mpadding
./bat.sh mpaste
./bat.sh mproduct
./bat.sh mrand
./bat.sh mrjoin
./bat.sh msed
./bat.sh msel
./bat.sh mselnum
./bat.sh mselrand
./bat.sh mselstr
./bat.sh msep
./bat.sh msetstr
./bat.sh mshare
./bat.sh mshuffle
./bat.sh msim
./bat.sh mslide
./bat.sh msortf
./bat.sh msplit
./bat.sh mstats
./bat.sh msum
./bat.sh msummary
./bat.sh mtab2csv
./bat.sh mtonull
./bat.sh mtra
./bat.sh mtrafld
./bat.sh mtraflg
./bat.sh muniq
./bat.sh mvcat
./bat.sh mvcommon
./bat.sh mvcount
./bat.sh mvdelim
./bat.sh mvdelnull
./bat.sh mvjoin
./bat.sh mvnullto
./bat.sh mvreplace
./bat.sh mvsort
./bat.sh mvuniq
./bat.sh mwindow
./bat.sh mxml2csv
#}
